#
# Copyright 2021, Stichting Kennisnet
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Timeout setting for communication with the Data Service
connection.timeout.seconds=2

# API settings
# Url of the API which returns the SSO Query information.
api.endpoint.url=

# The api-key header key and value - used in security purposes, is added to REST request
api.key.header.key=api-key
api.key.header.value=REPLACE-ME-WITH-A-VALID-TOKEN

# Fetch cache-hash schedule
dataservices.fetchCacheHash.cronSchedule=* 0/15 * * * *

# Cache-hash url
api.cacheHash.url=

# Indicate whether hostname wildcard functionality should be enabled. A configured url https://www.example.com will be
# changed to https://*.example.com which will match any subdomain before example.com, please note this is only applicable to
# one level.
host.wildcard.enabled=true

# Actuator expose settings
management.endpoints.web.exposure.include=health,info

# Logging settings
logging.level.root=INFO
logging.level.nl=DEBUG
# The location to the logback-spring.xml configuration file, for example /conf/logback-spring.xml within Docker.
logging.config=file:release/src/main/resources/sample/config/logback-spring.xml
logging.file.path=logs

data.location=file:release/src/main/resources/sample/config/idp.data.json
